import {ITmdbMenuItem, TmdbExploreSection} from "../interfaces";

const tmdbMenu: ITmdbMenuItem[] = [
    {
        section: 'movies',
        endpoint: 'discover',
        label: 'Discover',
        group: 'Movies',
        description: 'Explore movies with TMDB discover sorting.',
        path: '/discover/movie',
        kind: 'discover',
        resultType: 'movie',
        mediaType: 'movie',
        defaultParams: {sort_by: 'popularity.desc', include_adult: false},
        badge: 'Filters'
    },
    {
        section: 'movies',
        endpoint: 'popular',
        label: 'Popular',
        group: 'Movies',
        description: 'Movies currently popular on TMDB.',
        path: '/movie/popular',
        kind: 'list',
        resultType: 'movie',
        mediaType: 'movie',
        badge: 'List'
    },
    {
        section: 'movies',
        endpoint: 'top-rated',
        label: 'Top Rated',
        group: 'Movies',
        description: 'Highest rated movies.',
        path: '/movie/top_rated',
        kind: 'list',
        resultType: 'movie',
        mediaType: 'movie',
        badge: 'List'
    },
    {
        section: 'movies',
        endpoint: 'now-playing',
        label: 'Now Playing',
        group: 'Movies',
        description: 'Movies in theaters now.',
        path: '/movie/now_playing',
        kind: 'list',
        resultType: 'movie',
        mediaType: 'movie',
        badge: 'Live'
    },
    {
        section: 'movies',
        endpoint: 'upcoming',
        label: 'Upcoming',
        group: 'Movies',
        description: 'Upcoming theatrical releases.',
        path: '/movie/upcoming',
        kind: 'list',
        resultType: 'movie',
        mediaType: 'movie',
        badge: 'Soon'
    },
    {
        section: 'movies',
        endpoint: 'trending',
        label: 'Trending Week',
        group: 'Movies',
        description: 'Trending movies for the week.',
        path: '/trending/movie/week',
        kind: 'list',
        resultType: 'movie',
        mediaType: 'movie',
        badge: 'Week'
    },
    {
        section: 'movies',
        endpoint: 'trending-day',
        label: 'Trending Today',
        group: 'Movies',
        description: 'Trending movies for the current day.',
        path: '/trending/movie/day',
        kind: 'list',
        resultType: 'movie',
        mediaType: 'movie',
        badge: 'Day'
    },
    {
        section: 'movies',
        endpoint: 'search',
        label: 'Search',
        group: 'Movies',
        description: 'Search movies by title.',
        path: '/search/movie',
        kind: 'search',
        resultType: 'movie',
        mediaType: 'movie',
        requiresQuery: true,
        queryPlaceholder: 'Search movies',
        badge: 'Query'
    },
    {
        section: 'tv',
        endpoint: 'discover',
        label: 'Discover',
        group: 'TV',
        description: 'Explore TV shows with TMDB discover sorting.',
        path: '/discover/tv',
        kind: 'discover',
        resultType: 'tv',
        mediaType: 'tv',
        defaultParams: {sort_by: 'popularity.desc', include_adult: false},
        badge: 'Filters'
    },
    {
        section: 'tv',
        endpoint: 'popular',
        label: 'Popular',
        group: 'TV',
        description: 'TV shows currently popular on TMDB.',
        path: '/tv/popular',
        kind: 'list',
        resultType: 'tv',
        mediaType: 'tv',
        badge: 'List'
    },
    {
        section: 'tv',
        endpoint: 'top-rated',
        label: 'Top Rated',
        group: 'TV',
        description: 'Highest rated TV shows.',
        path: '/tv/top_rated',
        kind: 'list',
        resultType: 'tv',
        mediaType: 'tv',
        badge: 'List'
    },
    {
        section: 'tv',
        endpoint: 'airing-today',
        label: 'Airing Today',
        group: 'TV',
        description: 'TV shows airing today.',
        path: '/tv/airing_today',
        kind: 'list',
        resultType: 'tv',
        mediaType: 'tv',
        badge: 'Today'
    },
    {
        section: 'tv',
        endpoint: 'on-the-air',
        label: 'On The Air',
        group: 'TV',
        description: 'TV shows airing in the next seven days.',
        path: '/tv/on_the_air',
        kind: 'list',
        resultType: 'tv',
        mediaType: 'tv',
        badge: '7 days'
    },
    {
        section: 'tv',
        endpoint: 'trending',
        label: 'Trending Week',
        group: 'TV',
        description: 'Trending TV shows for the week.',
        path: '/trending/tv/week',
        kind: 'list',
        resultType: 'tv',
        mediaType: 'tv',
        badge: 'Week'
    },
    {
        section: 'tv',
        endpoint: 'trending-day',
        label: 'Trending Today',
        group: 'TV',
        description: 'Trending TV shows for the current day.',
        path: '/trending/tv/day',
        kind: 'list',
        resultType: 'tv',
        mediaType: 'tv',
        badge: 'Day'
    },
    {
        section: 'tv',
        endpoint: 'search',
        label: 'Search',
        group: 'TV',
        description: 'Search TV shows by name.',
        path: '/search/tv',
        kind: 'search',
        resultType: 'tv',
        mediaType: 'tv',
        requiresQuery: true,
        queryPlaceholder: 'Search TV shows',
        badge: 'Query'
    },
    {
        section: 'people',
        endpoint: 'popular',
        label: 'Popular',
        group: 'People',
        description: 'Popular people in movies and TV.',
        path: '/person/popular',
        kind: 'list',
        resultType: 'person',
        mediaType: 'person',
        badge: 'List'
    },
    {
        section: 'people',
        endpoint: 'trending',
        label: 'Trending Week',
        group: 'People',
        description: 'Trending people for the week.',
        path: '/trending/person/week',
        kind: 'list',
        resultType: 'person',
        mediaType: 'person',
        badge: 'Week'
    },
    {
        section: 'people',
        endpoint: 'trending-day',
        label: 'Trending Today',
        group: 'People',
        description: 'Trending people for the current day.',
        path: '/trending/person/day',
        kind: 'list',
        resultType: 'person',
        mediaType: 'person',
        badge: 'Day'
    },
    {
        section: 'people',
        endpoint: 'search',
        label: 'Search',
        group: 'People',
        description: 'Search people by name.',
        path: '/search/person',
        kind: 'search',
        resultType: 'person',
        mediaType: 'person',
        requiresQuery: true,
        queryPlaceholder: 'Search people',
        badge: 'Query'
    },
    {
        section: 'trending',
        endpoint: 'all-day',
        label: 'All Today',
        group: 'Trending',
        description: 'Trending movies, TV shows and people for the current day.',
        path: '/trending/all/day',
        kind: 'list',
        resultType: 'mixed',
        badge: 'Day'
    },
    {
        section: 'trending',
        endpoint: 'all-week',
        label: 'All Week',
        group: 'Trending',
        description: 'Trending movies, TV shows and people for the week.',
        path: '/trending/all/week',
        kind: 'list',
        resultType: 'mixed',
        badge: 'Week'
    },
    {
        section: 'search',
        endpoint: 'multi',
        label: 'Multi Search',
        group: 'Search',
        description: 'Search movies, TV shows and people with one query.',
        path: '/search/multi',
        kind: 'search',
        resultType: 'mixed',
        requiresQuery: true,
        queryPlaceholder: 'Search movies, TV, people',
        badge: 'Multi'
    },
    {
        section: 'find',
        endpoint: 'external-id',
        label: 'Find External ID',
        group: 'Search',
        description: 'Find TMDB records by external IDs such as IMDb IDs.',
        path: '/find/:externalId',
        kind: 'find',
        resultType: 'mixed',
        requiresQuery: true,
        externalSource: 'imdb_id',
        queryPlaceholder: 'Example: tt0133093',
        badge: 'Find'
    },
    {
        section: 'changes',
        endpoint: 'movie',
        label: 'Movie Changes',
        group: 'Changes',
        description: 'Movie records with recent data changes.',
        path: '/movie/changes',
        kind: 'list',
        resultType: 'change',
        mediaType: 'movie',
        badge: 'Recent'
    },
    {
        section: 'changes',
        endpoint: 'tv',
        label: 'TV Changes',
        group: 'Changes',
        description: 'TV records with recent data changes.',
        path: '/tv/changes',
        kind: 'list',
        resultType: 'change',
        mediaType: 'tv',
        badge: 'Recent'
    },
    {
        section: 'changes',
        endpoint: 'person',
        label: 'Person Changes',
        group: 'Changes',
        description: 'Person records with recent data changes.',
        path: '/person/changes',
        kind: 'list',
        resultType: 'change',
        mediaType: 'person',
        badge: 'Recent'
    },
    {
        section: 'genres',
        endpoint: 'movie',
        label: 'Movie Genres',
        group: 'Genres',
        description: 'Official TMDB movie genres.',
        path: '/genre/movie/list',
        kind: 'static',
        resultType: 'genre',
        badge: 'Static'
    },
    {
        section: 'genres',
        endpoint: 'tv',
        label: 'TV Genres',
        group: 'Genres',
        description: 'Official TMDB TV genres.',
        path: '/genre/tv/list',
        kind: 'static',
        resultType: 'genre',
        badge: 'Static'
    },
    {
        section: 'watch-providers',
        endpoint: 'movie',
        label: 'Movie Providers',
        group: 'Watch Providers',
        description: 'Streaming and purchase providers for movies.',
        path: '/watch/providers/movie',
        kind: 'static',
        resultType: 'provider',
        badge: 'Static'
    },
    {
        section: 'watch-providers',
        endpoint: 'tv',
        label: 'TV Providers',
        group: 'Watch Providers',
        description: 'Streaming and purchase providers for TV.',
        path: '/watch/providers/tv',
        kind: 'static',
        resultType: 'provider',
        badge: 'Static'
    },
    {
        section: 'watch-providers',
        endpoint: 'regions',
        label: 'Provider Regions',
        group: 'Watch Providers',
        description: 'Regions where watch provider data is available.',
        path: '/watch/providers/regions',
        kind: 'static',
        resultType: 'country',
        badge: 'Regions'
    },
    {
        section: 'collections',
        endpoint: 'search',
        label: 'Collections',
        group: 'Collections',
        description: 'Search movie collections and open their parts.',
        path: '/search/collection',
        kind: 'search',
        resultType: 'collection',
        requiresQuery: true,
        queryPlaceholder: 'Search collections',
        badge: 'Query'
    },
    {
        section: 'companies',
        endpoint: 'search',
        label: 'Companies',
        group: 'Companies',
        description: 'Search production companies and open company metadata.',
        path: '/search/company',
        kind: 'search',
        resultType: 'company',
        requiresQuery: true,
        queryPlaceholder: 'Search companies',
        badge: 'Query'
    },
    {
        section: 'keywords',
        endpoint: 'search',
        label: 'Keywords',
        group: 'Keywords',
        description: 'Search keywords and browse movies tagged with them.',
        path: '/search/keyword',
        kind: 'search',
        resultType: 'keyword',
        requiresQuery: true,
        queryPlaceholder: 'Search keywords',
        badge: 'Query'
    },
    {
        section: 'certifications',
        endpoint: 'movie',
        label: 'Movie Certifications',
        group: 'Certifications',
        description: 'Official movie certification systems by country.',
        path: '/certification/movie/list',
        kind: 'static',
        resultType: 'certification',
        badge: 'Static'
    },
    {
        section: 'certifications',
        endpoint: 'tv',
        label: 'TV Certifications',
        group: 'Certifications',
        description: 'Official TV certification systems by country.',
        path: '/certification/tv/list',
        kind: 'static',
        resultType: 'certification',
        badge: 'Static'
    },
    {
        section: 'configuration',
        endpoint: 'languages',
        label: 'Languages',
        group: 'Configuration',
        description: 'Languages available in TMDB metadata.',
        path: '/configuration/languages',
        kind: 'static',
        resultType: 'language',
        badge: 'Static'
    },
    {
        section: 'configuration',
        endpoint: 'countries',
        label: 'Countries',
        group: 'Configuration',
        description: 'Countries available in TMDB metadata.',
        path: '/configuration/countries',
        kind: 'static',
        resultType: 'country',
        badge: 'Static'
    },
    {
        section: 'configuration',
        endpoint: 'timezones',
        label: 'Timezones',
        group: 'Configuration',
        description: 'Timezones available in TMDB metadata.',
        path: '/configuration/timezones',
        kind: 'static',
        resultType: 'timezone',
        badge: 'Static'
    },
    {
        section: 'configuration',
        endpoint: 'images',
        label: 'Image Config',
        group: 'Configuration',
        description: 'TMDB image base URLs and supported sizes.',
        path: '/configuration',
        kind: 'static',
        resultType: 'configuration',
        badge: 'Images'
    },
    {
        section: 'configuration',
        endpoint: 'jobs',
        label: 'Jobs',
        group: 'Configuration',
        description: 'Department and job names used in credits.',
        path: '/configuration/jobs',
        kind: 'static',
        resultType: 'job',
        badge: 'Static'
    },
    {
        section: 'configuration',
        endpoint: 'primary-translations',
        label: 'Primary Translations',
        group: 'Configuration',
        description: 'Primary translation locales supported by TMDB.',
        path: '/configuration/primary_translations',
        kind: 'static',
        resultType: 'translation',
        badge: 'Locales'
    }
];

const tmdbMenuSections: TmdbExploreSection[] = [
    'movies',
    'tv',
    'people',
    'trending',
    'search',
    'find',
    'changes',
    'genres',
    'watch-providers',
    'collections',
    'companies',
    'keywords',
    'certifications',
    'configuration'
];

const getTmdbMenuItem = (section: string, endpoint: string): ITmdbMenuItem | undefined =>
    tmdbMenu.find(item => item.section === section && item.endpoint === endpoint);

const getTmdbExplorePath = (item: ITmdbMenuItem): string => `/explore/${item.section}/${item.endpoint}?page=1`;

export {
    getTmdbExplorePath,
    getTmdbMenuItem,
    tmdbMenu,
    tmdbMenuSections
};
